# File: .github/workflows/update.yml
name: "Auto-update Roblox YouTube Channels"
on:
  schedule:
    # Runs every 5 minutes
    - cron: '*/5 * * * *'
  workflow_dispatch:  # Allows manual “Run workflow” from GitHub UI

jobs:
  update_players_json:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pytest

      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings -q

      - name: Run main.py to update players.json
        env:
          YT_API_KEY: ${{ secrets.YT_API_KEY }}
        run: |
          python main.py 50

      - name: Commit and push changes
        run: |
          # If players.json was modified, commit and push back to the repo
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if [[ -n "$(git status --porcelain players.json)" ]]; then
            git add players.json
            git commit -m "Auto-update players.json: $(date -u +'%Y-%m-%d %H:%M:%S') UTC"
            git push
          else
            echo "No changes to players.json"
          fi

