# .github/workflows/autoupdate.yml
name: Auto‐update Roblox YouTubers

# 1) Grant write access to contents so our bot can push players.json changes
permissions:
  contents: write

on:
  schedule:

    - cron: '*/1 * * * *'
  workflow_dispatch:

jobs:
  update-players:
    runs-on: ubuntu-latest

    steps:
      # 2) Check out the repository, with credentials persisted so we can push
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # Ensure that the GITHUB_TOKEN can be used by subsequent steps to push
          persist-credentials: true

      # 3) Set up Python
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # 4) Install youtube API client
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-api-python-client
      - name: Run update script
        run: python main.py
      - name: Commit & push updated players.json
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
       
          file_pattern: players.json
       
          commit_message: "Auto‐update players.json (Roblox YouTubers) — ${{ github.event_name }} @ ${{ github.run_id }}"
    
          branch: ${{ github.ref_name }}
          author_name: github-actions
          author_email: github-actions@github.com
